import {  Nunito} from "next/font/google"; 
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"


const geistSans = Nunito({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Choco Loca - Cakes & Cafe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
